"""Add warehouse fields

Revision ID: 36d246231384
Revises: 72e567e0c17b
Create Date: 2024-01-03 16:11:00.840272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36d246231384"
down_revision: Union[str, None] = "72e567e0c17b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("delivery_status", sa.Column("source_warehouse", sa.Integer(), nullable=False))
    op.add_column("order", sa.Column("source_warehouse", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "source_warehouse")
    op.drop_column("delivery_status", "source_warehouse")
    # ### end Alembic commands ###
