"""Add photo URL field to user

Revision ID: 5a3849708b3e
Revises: 388e61c0df62
Create Date: 2023-12-30 17:56:36.369925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3849708b3e'
down_revision: Union[str, None] = '388e61c0df62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_url')
    # ### end Alembic commands ###
