"""Change photo_url to photo_base64 in User table

Revision ID: 861c8fb41e7b
Revises: df87900a1961
Create Date: 2024-01-04 20:17:38.222028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861c8fb41e7b'
down_revision: Union[str, None] = 'df87900a1961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_base64', sa.String(), nullable=True))
    op.drop_column('user', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'photo_base64')
    # ### end Alembic commands ###
