"""Add main field, add warehouse object

Revision ID: a151e28e52ea
Revises: ba87632e217a
Create Date: 2024-01-03 12:09:35.217998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a151e28e52ea'
down_revision: Union[str, None] = 'ba87632e217a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('manager', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('category', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('warehouse', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('total_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'total_count')
    op.drop_column('product', 'warehouse')
    op.drop_column('product', 'category')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
