"""Change warehouse fields

Revision ID: d6c048de272a
Revises: 36d246231384
Create Date: 2024-01-03 19:35:21.517793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c048de272a'
down_revision: Union[str, None] = '36d246231384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_position',
    sa.Column('warehouse', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('unic_id', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('warehouses', sa.Integer(), nullable=False))
    op.drop_column('product', 'warehouse')
    op.drop_column('product', 'total_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('warehouse', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product', 'warehouses')
    op.drop_table('warehouse_position')
    # ### end Alembic commands ###
