"""Change to full_nm field in User table

Revision ID: df87900a1961
Revises: 61a88ebe2933
Create Date: 2024-01-04 13:42:14.063207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df87900a1961'
down_revision: Union[str, None] = '61a88ebe2933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_nm', sa.String(), nullable=True))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'full_nm')
    # ### end Alembic commands ###
